### ISSUE TITLE
Request to update `Cargo.lock`

### ISSUE THREAD

**Issue by wszqkzqk** [ammgws/autotiling-rs#17]
The current `Cargo.lock` has not been updated for two years and it's not compatible with newly supported architectures. Also, it might miss upstream security updates. Shall we update it to fix these things?

**Comment by ammgws** [comment]
PRs welcome! :)

**Comment by ammgws** [comment]
Does 5476582d5e6d4592adcf01bd4678a647ba306003 help?

**Comment by wszqkzqk** [comment]
> Does [5476582](https://github.com/ammgws/autotiling-rs/commit/5476582d5e6d4592adcf01bd4678a647ba306003) help?

It seems not. I tried to build in a clean chroot of archlinux, and it failed with:

```log
patching file Cargo.lock
    Updating crates.io index
error: the lock file /build/autotiling-rs/src/autotiling-rs-0.1.3/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```

**Comment by wszqkzqk** [comment]
OK, thank you!

**Comment by ammgws** [comment]
By the way which arch do you have that was having issues building?

**Comment by wszqkzqk** [comment]
> By the way which arch do you have that was having issues building?

It's [LOONGARCH 64 bit](https://docs.kernel.org/arch/loongarch/introduction.html)
