### ISSUE TITLE
Support —workspaces

### ISSUE THREAD

**Issue by adworacz** [ammgws/autotiling-rs#4]
Just like the python version of autotiling, can you add support for specifying which workspaces autotiling should take effect?

ex: 
`autotiling-rs —workspaces 1 3 5`

**Comment by ammgws** [comment]
I wouldn't be opposed to a PR implementing it.

**Comment by adworacz** [comment]
Hmmm okay, I don't know Rust at all, but if I have some free time I may give it a shot.

**Comment by ammgws** [comment]
Closed via #5
